name: Greet Someone

on:
  push:
    branches:
      - feature/greeting
      - main

jobs:
  call-greet:
    uses: ./.github/workflows/reusable-greet.yml
    with:
      person-name: Fred
    secrets:
      greeting-key: ${{ secrets.GREETING_KEY }}