name: Greet Someone

on:
  push:
    branches:
      - feature/greeting
      - main

jobs:
  call-greet:
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/feature/greeting'
    strategy:
      matrix:
        person-name: [Fred, Alice, Bob]  # List of names to loop over
    uses: ./.github/workflows/reusable-greet.yml
    with:
      person-name: ${{ matrix.person-name }}
    secrets:
      greeting-key: ${{ secrets.GREETING_KEY }}